function stim = pedtextplay(ax, stim)
%% Draw text
stim.Obj = text(ax, ... % Create a text object...
    'EdgeColor', 'none', ... % ...with no edge...
    'FontSize', 20, ... % ...font size 20...
    'Position', [stim.Pos(1) stim.Pos(2)], ... % ...at a user-specified position...
    'String', stim.Text ... % ...containing the string specified by the user
    ); 